[system]
compatible=radxa-zero-ruview
bootloader=uboot
statusfile=/data/rauc.status

[keyring]
path=/etc/rauc/keyring.pem

[slot.rootfs.0]
device=/dev/mmcblk0p3
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/mmcblk0p4
type=ext4
bootname=B
