BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
LAYERVERSION_meta-ruview = "1"
LAYERDEPENDS_meta-ruview = "core"
LAYERSERIES_COMPAT_meta-ruview = "scarthgap"
